[manager]

keymap = [
  # NOTE: This is a reversal of both keybinds
  # Because we don't need to trash an item in Yazi
  { on = "d", run = "remove --permanently", desc = "Permanently delete selected files" },

  # ... but in case we do...
  { on = "D", run = "remove", desc = "Permanently delete selected files" },
]
